### ISSUE TITLE
Development environment for testing web

### ISSUE THREAD

**Issue by MihaMarkic** [yuvaltz/Granular#4]
It'd be good if somebody (the author) provides steps to create development environment for web.
For WPF I merely add projects to solution and reference them instead of ones referenced by NuGet package.
For Web I tried the same but then build process complains. First that Transform is ambigous. Once I fix that it requires some other system assemblies referenced and what's not. Plus steps to compile libraries (I guess that's just a few MSBuild tasks in the project).
Anyway, some steps or a skeleton app ready for web testing (testing code modifications, not frontend application) would be nice.

**Comment by yuvaltz** [comment]
Basically what you've done is right, have you referenced the "Web" dlls? (e.g. from ..\Granular.Presentation.Web\bin\Debug)

I'll add the necessary steps to the wiki later today.

**Comment by MihaMarkic** [comment]
Yep, one of them wasn't web. Now it is better. I still had to add a bunch of System.* assemblies and getting this error:

2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999: INTERNAL ERROR: System.TypeLoadException: Type 'System.Runtime.CompilerServices.CompilationRelaxationsAttribute' not found in assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a4048e8fcc593f14'
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at IKVM.Reflection.Universe.GetMissingTypeOrThrow(Module requester, Module module, Type declaringType, TypeName typeName)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at IKVM.Reflection.Assembly.ResolveType(Module requester, TypeName typeName)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at IKVM.Reflection.Module.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at IKVM.Reflection.Reader.ModuleReader.GetMemberRef(Int32 index, Type[] genericTypeArguments, Type[] genericMethodArguments)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at IKVM.Reflection.Reader.ModuleReader.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at IKVM.Reflection.CustomAttributeData.get_Constructor()
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.AddCustomAttributes(IEnumerable`1 attributes, ICollection`1 targetCollection)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.AddAttributes(Assembly assembly, IList`1 outputList)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at ICSharpCode.NRefactory.TypeSystem.IkvmLoader.LoadAssembly(Assembly assembly)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at Saltarelle.Compiler.Driver.CompilerDriver.<LoadReferences>b__27(Assembly asm)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at Saltarelle.Compiler.Driver.CompilerDriver.LoadReferences(IEnumerable`1 references, IErrorReporter er)
2>g:\temp\tempprojects\TestGranular\packages\Saltarelle.Compiler.2.6.2\tools\Saltarelle.Compiler.targets(32,3): error CS7999:    at Saltarelle.Compiler.Driver.CompilerDriver.Compile(CompilerOptions options). Please report this as an issue on https://github.com/erik-kallen/SaltarelleCompiler/

**Comment by yuvaltz** [comment]
If it compiles with the dll from the package, there is no reason for it not to compile with dll from "..\Granular.Presentation.Web\bin\Debug", it should be the same dll. Definitely there is no need to add System.* references.
(I know that VS shows "design time" errors when opening a xaml or a cs file with classes that are defined both in WindowsBase or PresentationCore and in Granular, just ignore them, they're not real errors, it still compiles)

**Comment by MihaMarkic** [comment]
Something went wrong within the project. I created new, clean, "web" project and now it compiles find. Thanks.
